print("###################################")
print("#                                 #")
print("#   Gusti Muhammad Naufal Razin   #")
print("#         2210817210002           #")
print("#                                 #")
print("###################################")